In [147]:
import imagehash, cv2
from PIL import Image
import matplotlib.pyplot as plt
from matplotlib import cm
import numpy as np

In [177]:
x_arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
temp = map(tuple, x_arr)
x_tup = tuple(temp)
x_tup

((1, 2, 3), (4, 5, 6), (7, 8, 9))

In [148]:
# fig = plt.figure(figsize=(w,h), dpi=dpi)
#     fig.figimage(sub, cmap=cm.gist_earth)

In [149]:
image1 = Image.open('images/cat.jpg')
image2 = Image.open('images/cat_cr.jpg')

In [150]:
hash1 = imagehash.phash(image1)
hash2 = imagehash.phash(image2)
print(hash1)
print(hash2)

9151e66a4b4c6ea7
9151e66a4bcc6ee4


In [151]:
print(type(hash1))
print(hash1.hash.size)

<class 'imagehash.ImageHash'>
64


In [195]:
# myArray = cv2.imread('images/pixil-frame-0.png')
myArray2 = cv2.imread('images/pixil-frame-0.png')
print(myArray2)

[[[ 99  30 233]
  [ 99  30 233]
  [ 99  30 233]
  ...
  [  0   0 213]
  [  0   0 213]
  [  0   0 213]]

 [[181  81  63]
  [ 57 220 205]
  [ 57 220 205]
  ...
  [  0   0 213]
  [  0   0 213]
  [  0   0 213]]

 [[181  81  63]
  [ 57 220 205]
  [ 57 220 205]
  ...
  [  0   0 213]
  [  0   0 213]
  [  0   0 213]]

 ...

 [[ 57 220 205]
  [ 57 220 205]
  [ 57 220 205]
  ...
  [ 47  47 211]
  [ 47  47 211]
  [ 47  47 211]]

 [[ 57 220 205]
  [ 57 220 205]
  [ 57 220 205]
  ...
  [ 47  47 211]
  [ 47  47 211]
  [ 47  47 211]]

 [[ 57 220 205]
  [ 57 220 205]
  [ 57 220 205]
  ...
  [ 47  47 211]
  [ 47  47 211]
  [ 47  47 211]]]


In [196]:
myArray = myArray / myArray.max()

In [197]:
myArray.max()

1.0

In [202]:
# im = Image.fromarray(np.uint8(cm.ScalarMappable(myArray)*255))
im2 = Image.fromarray(myArray2, 'RGB')

In [205]:
im2.save('images/out3.jpg')

In [211]:
pixels = np.array([[[255, 0, 0], [0, 255, 0]], [[0, 0, 255], [255, 255, 0]]])
print(pixels.shape)
image = Image.fromarray(pixels.astype('uint8'), 'RGB')

# Print out the pixel values
print(image.getpixel((0, 0)))
print(image.getpixel((0, 1)))
print(image.getpixel((1, 0)))
print(image.getpixel((1, 1)))

# Save the image
image.save('images/imageout.png')

(2, 2, 3)
(255, 0, 0)
(0, 0, 255)
(0, 255, 0)
(255, 255, 0)


In [214]:
import matplotlib.pyplot as plt
plt.imsave('images/newOut.png', myArray2, cmap='Greys')